# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "tmp_function": "00_core.ipynb",
         "new_function": "00_core.ipynb",
         "new_fun": "00_core.ipynb",
         "takeaway": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://leanne-kim.github.io/implementingnbdev/"

git_url = "https://github.com/leanne-kim/implementingnbdev/tree/master/"

def custom_doc_links(name): return None
