# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'tmp_function', 'new_function', 'new_fun']

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# Cell
def tmp_function():
    print("This is working")
    return;

# Cell
def new_function():
    print("some new func")
    return;

# Cell
def new_fun(x, y):
    return x+y;